### ISSUE TITLE
Muito bom gostei bem também comecei a fazer um jogo já dá pra jogar 

### ISSUE THREAD

**Issue by Leone800** [PetersonPHC/Trabalho_semestral_Mobile-Android#1]
Parabéns

**Comment by Peterson-FatecZl** [comment]
Que legal, manda o link do projeto aqui pra gente visualizar 💪🏻

**Comment by PetersonPHC** [comment]
Que legal, manda o link do projeto aqui pra gente visualizar 💪🏻
Vou ter acompanhar lá 😉
